version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flexflag-postgres
    environment:
      POSTGRES_USER: flexflag
      POSTGRES_PASSWORD: flexflag
      POSTGRES_DB: flexflag
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flexflag"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flexflag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
    container_name: flexflag-server
    ports:
      - "8080:8080"
    environment:
      FLEXFLAG_DATABASE_HOST: postgres
      FLEXFLAG_DATABASE_PORT: 5432
      FLEXFLAG_DATABASE_USERNAME: flexflag
      FLEXFLAG_DATABASE_PASSWORD: flexflag
      FLEXFLAG_DATABASE_DATABASE: flexflag
      FLEXFLAG_REDIS_HOST: redis
      FLEXFLAG_REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: